/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculatorRouteImport } from './routes/calculator'

const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/calculator': typeof CalculatorRoute
}
export interface FileRoutesByTo {
  '/calculator': typeof CalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calculator': typeof CalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/calculator'
  id: '__root__' | '/calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CalculatorRoute: typeof CalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CalculatorRoute: CalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
